/**
 * Peptide enrichment data — curated facts/figures scraped from peptidedosages.com.
 *
 * REFERENCE ONLY. Attributed to peptidedosages.com on every entry. This is NOT
 * medical advice and NOT for use by anyone other than the operator. Dose numbers
 * are educational reference figures lifted from the source's published charts.
 *
 * Two read paths (see {@link getEnrichmentSeed} / {@link getEnrichment}):
 *   - sync  : reads the committed seed JSON (works offline / before any refresh)
 *   - async : prefers a fresh DB row (PeptideReference), falls back to the seed
 *
 * The seed is generated by `scripts/scrape-peptidedosages.mjs`. The weekly
 * refresh endpoint (`POST /api/enrichment/refresh`) re-runs the scrape and
 * upserts PeptideReference rows; the async reader prefers those.
 */

import seedData from "./data/peptide-enrichment.json";
import { applySupplement } from "./enrichment/manual-supplement";

export const ENRICHMENT_SOURCE = "peptidedosages.com" as const;

/**
 * A protocol EXAMPLE template — an illustrative starting point the UI can offer
 * to pre-fill the protocol/calculator forms. NOT a prescription.
 */
export interface EnrichmentTemplate {
  /** Human label, e.g. "Standard / Gradual Approach". */
  name: string;
  /** What `targetDose` is expressed against. */
  doseBasis: "per_injection" | "per_week";
  /** Numeric dose at the maintenance / top phase (the headline figure). */
  targetDose: number | null;
  /** Unit for `targetDose` and ramp steps: mcg | mg | iu. */
  unit: string;
  /** Free-text frequency / schedule hint, e.g. "Once weekly subcutaneous". */
  frequency: string | null;
  /** Optional titration ramp — ordered phases from the source's dose chart. */
  ramp?: EnrichmentRampStep[];
}

/** One row of a titration ramp (a phase in the source's dose chart). */
export interface EnrichmentRampStep {
  /** Phase label as published, e.g. "Weeks 1–4" or "Weeks 1-2". */
  phase: string;
  /** Dose for the phase, in `unit`. */
  dose: number | null;
  /** Unit for `dose` (mcg | mg | iu); may differ per row but normally matches the template. */
  unit: string;
  /** Verbatim dose cell, kept for display when parsing the number is ambiguous. */
  doseLabel: string;
}

/** A reference citation extracted from the source's References list. */
export interface EnrichmentReference {
  /** Short citation text (publication / author / topic). */
  label: string;
  /** Outbound source URL, where present. */
  url: string | null;
}

/** The enrichment payload for a single peptide. */
export interface EnrichmentEntry {
  /** Canonical peptide name as it appears in PEPTIDE_LIBRARY. */
  name: string;
  /** Comma-separated aliases (mirrors LibraryPeptide.aliases), if any. */
  aliases?: string;
  /** Short factual summaries of benefits/uses. */
  benefits: string[];
  /** Short factual summaries of side-effects / symptoms to watch. */
  sideEffects: string[];
  /** Dose-range reference summary (the source's headline dosing sentence). */
  dosingReference: string | null;
  /** Reconstitution guidance steps. */
  reconstitution: string[];
  /** Reconstitution ratio hint if published, e.g. "2 mL = ~10.0 mg/mL". */
  reconstitutionRatio: string | null;
  /** Mechanism-of-action summary. */
  mechanism: string | null;
  /** Example protocol templates (titration ramps + frequency). */
  templates: EnrichmentTemplate[];
  /** Source references / citations. */
  references: EnrichmentReference[];
  /** Always "peptidedosages.com". */
  source: typeof ENRICHMENT_SOURCE;
  /** The specific source page URL this entry was scraped from. */
  sourceUrl: string;
  /** Attribution line for the UI disclaimer. */
  attribution: string;
  /** ISO timestamp the seed was curated (scrape run time). */
  curatedAt: string;
}

/** The shape of the committed seed file. */
export interface EnrichmentSeed {
  generatedAt: string;
  source: string;
  entries: EnrichmentEntry[];
}

const seed = seedData as EnrichmentSeed;

/**
 * Tokenise a name + comma-separated aliases into lowercase match tokens.
 * Mirrors the `tokens()` helper in settings/page.tsx so library/owned/enrichment
 * matching stays consistent.
 */
export function tokens(name: string, aliases?: string): string[] {
  return [name, ...(aliases ?? "").split(",")]
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
}

/** Build a token set for an entry (its own name + aliases). */
function entryTokens(e: EnrichmentEntry): Set<string> {
  return new Set(tokens(e.name, e.aliases));
}

/** Case-insensitive name/alias match against the seed entries. */
function matchSeed(name: string, aliases?: string): EnrichmentEntry | undefined {
  const want = tokens(name, aliases);
  if (want.length === 0) return undefined;
  return seed.entries.find((e) => {
    const have = entryTokens(e);
    return want.some((t) => have.has(t));
  });
}

/**
 * SYNC lookup from the committed seed JSON. Case-insensitive by name or alias.
 * Returns undefined for unknown peptides. Safe to call from server components /
 * client bundles (no DB access).
 */
export function getEnrichmentSeed(name: string, aliases?: string): EnrichmentEntry | undefined {
  const found = matchSeed(name, aliases);
  return found ? applySupplement(found) : undefined;
}

/** All seed entries (for listing / debugging). */
export function allEnrichmentSeed(): EnrichmentEntry[] {
  return seed.entries;
}

/** Seed metadata (generation time + source). */
export function enrichmentSeedMeta(): { generatedAt: string; source: string; count: number } {
  return { generatedAt: seed.generatedAt, source: seed.source, count: seed.entries.length };
}

/**
 * ASYNC lookup: prefer a fresh DB row (PeptideReference), fall back to the seed.
 *
 * The DB row stores the EnrichmentEntry as JSON in `dataJson`. When the table is
 * empty or this peptide has no row, we return the seed entry. A malformed /
 * unparseable DB row also falls back to the seed (never throws on bad data).
 *
 * DB access is dynamically imported so this module stays importable from the
 * Edge runtime / client bundles that only need {@link getEnrichmentSeed}.
 */
export async function getEnrichment(name: string, aliases?: string): Promise<EnrichmentEntry | undefined> {
  const want = tokens(name, aliases);
  if (want.length === 0) return undefined;

  try {
    const { prisma } = await import("./db");
    // Match the DB row by any of the wanted tokens against its peptideName.
    const rows = await prisma.peptideReference.findMany();
    for (const row of rows) {
      const rowTokens = tokens(row.peptideName);
      if (!want.some((t) => rowTokens.includes(t))) continue;
      try {
        const parsed = JSON.parse(row.dataJson) as EnrichmentEntry;
        // Trust the row's source/curatedAt if present; otherwise stamp from the row.
        return applySupplement({
          ...parsed,
          source: ENRICHMENT_SOURCE,
          sourceUrl: parsed.sourceUrl ?? row.source,
          curatedAt: parsed.curatedAt ?? row.fetchedAt.toISOString(),
        });
      } catch {
        // Malformed row JSON — fall through to seed.
        break;
      }
    }
  } catch {
    // DB unavailable (Edge / build / no migration yet) — fall back to seed.
  }

  const found = matchSeed(name, aliases);
  return found ? applySupplement(found) : undefined;
}
